# Resolve react_native_pods.rb with node to allow for hoisting
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Setup permissions
setup_permissions([
  'Camera',
  'PhotoLibrary',
  'Notifications',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'snaplink' do
  config = use_native_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix react-native-date-picker missing string header for Xcode 26+
    date_picker_files = [
      '../node_modules/react-native-date-picker/ios/RNDatePickerManager.mm',
      '../node_modules/react-native-date-picker/ios/RNDatePicker.mm'
    ]

    date_picker_files.each do |file_path|
      file = File.join(File.dirname(__FILE__), file_path)
      if File.exist?(file)
        contents = File.read(file)
        unless contents.include?('#include <string>')
          # Add #include <string> at the very top of the file
          new_contents = "#include <string>\n" + contents
          File.write(file, new_contents)
          puts "Fixed #{file_path} - added missing <string> header"
        end
      end
    end
  end
end
