# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'json'

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_P8_CONTENT"],
      is_key_content_base64: true
    )

    increment_build_number(
      xcodeproj: "snaplink.xcodeproj",
      build_number: latest_testflight_build_number(api_key: api_key) + 1
    )

    json_path = File.join(File.dirname(__FILE__), "../../package.json")
    package = JSON.parse(File.read(json_path))
    package_version = package["version"]
    
    increment_version_number(
      xcodeproj: "snaplink.xcodeproj",
      version_number: package_version
    )

    profile_name = ENV["IOS_PROVISIONING_PROFILE_NAME"] || "match AppStore com.revede.snaplink"
    app_identifier = ENV["IOS_APP_IDENTIFIER"] || "com.revede.snaplink"

    build_app(
      workspace: "snaplink.xcworkspace",
      scheme: "snaplink",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "../build/ios",
      skip_profile_detection: true,
      export_options: {
        provisioningProfiles: { app_identifier => profile_name }
      },
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='#{profile_name}' ENABLE_USER_SCRIPT_SANDBOXING=NO",
      silent: false,
      suppress_xcode_output: false
    )

    upload_to_testflight(api_key: api_key, skip_waiting_for_build_processing: true)
  end

  desc "Download certificates and provisioning profiles"
  lane :certificates do
    match(type: "appstore", readonly: true, app_identifier: "com.revede.snaplink")
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "snaplink.xcodeproj")
    build_app(
      workspace: "snaplink.xcworkspace",
      scheme: "snaplink",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "../build/ios",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='match AppStore com.revede.snaplink'"
    )
    upload_to_app_store(skip_metadata: false, skip_screenshots: true, submit_for_review: false)
  end

end