# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'json'

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Play Store (Internal Testing)"
  lane :beta do
    timestamp_code = Time.now.to_i
    gradle_path = File.join(File.dirname(__FILE__), "../app/build.gradle")
    gradle_content = File.read(gradle_path)
    new_gradle_content = gradle_content.gsub(/versionCode \d+/, "versionCode #{timestamp_code}")
    File.write(gradle_path, new_gradle_content)

    gradle(task: "bundle", build_type: "Release")

    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  def get_package_version
    json_path = File.join(File.dirname(__FILE__), "../../package.json")
    package = JSON.parse(File.read(json_path))
    package["version"]
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    package_version = get_package_version
    timestamp_code = Time.now.to_i
    gradle_path = File.join(File.dirname(__FILE__), "../app/build.gradle")
    gradle_content = File.read(gradle_path)
    gradle_content = gradle_content.gsub(/versionName "[^"]*"/, "versionName \"#{package_version}\"")
    gradle_content = gradle_content.gsub(/versionCode \d+/, "versionCode #{timestamp_code}")
    File.write(gradle_path, gradle_content)

    gradle(task: "bundle", build_type: "Release")

    upload_to_play_store(
      track: "production",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end